### ISSUE TITLE
Error: Invalid function argument on .terraform/modules/postgres/postgresconfig.tf

### ISSUE THREAD

**Issue by flavio-santino** [oracle-devrel/terraform-oci-cloudbricks-postgresql#3] opened 2021-11-04 19:11 UTC
Hello team, when executing this module we are getting this error message:

```
Error: Invalid function argument on .terraform/modules/postgres/postgresconfig.tf line 9, in data "template_file" "postgresql_install_binaries_sh":
9:   template = file("scripts/postgresql_install_binaries.sh")
Invalid value for "path" parameter: no file exists at scripts/postgresql_install_binaries.sh; this function works only with files that are distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this result from an attribute of that resource.
```
It is basically losing the reference on the scripts when used as a module.

Thank you, 
--Flavio

**Comment by dralquinta** [comment] 2021-11-04 19:31
Problem seems to be around the fact that when brick is used as a module, it'll lose the reference around where the script is, causing the exception to happen.

Steps to reproduce: 

- When using the module and running init, the following will happen: 


```shell
[opc@dalquintdevhubscl postgresql]$ terraform validate
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/postgre01/postgresconfig.tf line 9, in data "template_file" "postgresql_install_binaries_sh":
│    9:   template = file("scripts/postgresql_install_binaries.sh")
│ 
│ Invalid value for "path" parameter: no file exists at scripts/postgresql_install_binaries.sh; this function works only with files that are distributed as part of the configuration source code, so
│ if this file will be created by a resource in this configuration you must instead obtain this result from an attribute of that resource.

```

This will happen for every single thing that uses a script to work. 

Investigating further

**Comment by dralquinta** [comment] 2021-11-04 19:43
Managed to fix the problem. 

Issue is resolved by setting a relative reference in code to scripting as follows:

Change this: 

```shell
data "template_file" "postgresql_install_binaries_sh" {
  template = file("scripts/postgresql_install_binaries.sh")

  vars = {
    pg_password       = var.postgresql_password
    pg_version_no_dot = replace(var.postgresql_version, ".", "")
    pg_version        = var.postgresql_version
  }
}
```

for this:

```shell
data "template_file" "postgresql_install_binaries_sh" {
  template = file("${path.module}/scripts/postgresql_install_binaries.sh")

  vars = {
    pg_password       = var.postgresql_password
    pg_version_no_dot = replace(var.postgresql_version, ".", "")
    pg_version        = var.postgresql_version
  }
}
```

I'll push the fix next, after unitary testing is done

**Comment by dralquinta** [comment] 2021-11-04 19:50
Unit testing done.

Snippet of destruction: 

```shell
module.postgre01.oci_core_instance.postgresql_hotstandby2[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...f3gbiwei63du4hlug7o7s4tqvrwudcib6dtwua, 50s elapsed]
module.postgre01.oci_core_instance.postgresql_master: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...ds4sqphrfa2ctkgroprseibrbitjooaew6ikoa, 1m0s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...nfhdyrhdzlkmnpn5vvdj44f5jrht3tv6hpmg3a, 50s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby2[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...f3gbiwei63du4hlug7o7s4tqvrwudcib6dtwua, 1m0s elapsed]
module.postgre01.oci_core_instance.postgresql_master: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...ds4sqphrfa2ctkgroprseibrbitjooaew6ikoa, 1m10s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...nfhdyrhdzlkmnpn5vvdj44f5jrht3tv6hpmg3a, 1m0s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby2[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...f3gbiwei63du4hlug7o7s4tqvrwudcib6dtwua, 1m10s elapsed]
module.postgre01.oci_core_instance.postgresql_master: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...ds4sqphrfa2ctkgroprseibrbitjooaew6ikoa, 1m20s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...nfhdyrhdzlkmnpn5vvdj44f5jrht3tv6hpmg3a, 1m10s elapsed]
module.postgre01.oci_core_instance.postgresql_master: Destruction complete after 1m24s
module.postgre01.oci_core_instance.postgresql_hotstandby2[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...f3gbiwei63du4hlug7o7s4tqvrwudcib6dtwua, 1m20s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...nfhdyrhdzlkmnpn5vvdj44f5jrht3tv6hpmg3a, 1m20s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby2[0]: Destruction complete after 1m24s
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Still destroying... [id=ocid1.instance.oc1.sa-santiago-1.anzwgl...nfhdyrhdzlkmnpn5vvdj44f5jrht3tv6hpmg3a, 1m30s elapsed]
module.postgre01.oci_core_instance.postgresql_hotstandby1[0]: Destruction complete after 1m34s

Destroy complete! Resources: 41 destroyed.
```

**Closed as completed by dralquinta** 2021-11-04 19:50 UTC
Labels: bug

**Comment by flavio-santino** [comment] 2021-11-04 19:52
Great work @dralquinta 
Thank you!
